# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/setup.md
fos_elastica:
  clients:
    default: { host: localhost, port: 9200 }
  indexes:
    app:
      settings:
        index:
          analysis:
            analyzer:
              default:
                type: french
      index_name: app_%kernel.environment%
      types:
        projet:
          properties:
            titre: ~
            description: ~
            date_debut_inscription: ~
            date_fin_inscription: ~
            domaine:
              type: "object"
              properties:
                id: ~
                categorie: ~
            user:
              type: "object"
              properties:
                id: ~
                prenom: ~
                nom: ~
          persistence:
            # the driver can be orm, mongodb or phpcr
            driver: orm
            model: App\Entity\Projet
            provider: ~
            finder: ~